### ISSUE TITLE
@BibianaLee Here is the issues ticket thing

### ISSUE THREAD

**Issue by nbir012** [nbir012/diptera-morphometrics#1]

**Comment by nbir012** [comment]
@BibianaLee

**Comment by BibianaLee** [comment]
Hi Niel 

Your Team Charter looks good! You have covered everything in sufficient detail and have clearly established the direction and scope of your project. I particularly like your behavior agreement as  it demonstrates your openness to change and improvement . This project has to be completed within a short period of time so a positive and open attitude is going to be necessary. 

The only thing I would maybe look at is your criteria for success. You could identify specific programs for your analysis and mention the final report in the list. There is also a very small spelling mistake in the communication agreement. 

Additionally, I think it is always important to explicitly state which channels you will go through when addressing problems. This way you ensure that you yourself have gone through the proper channels and others are aware of this when you approach them for help. 

Overall, your team charter is well-thought-out and easy to follow

**Comment by nbir012** [comment]
Thanks Bibiana, 

Those are valid points and I have adjusted the team charter accordingly

All the best!

Neil

**Comment by BibianaLee** [comment]
Hey Neil, 
Your changes back in August looked good :) 
closing the issue now
